on:
  repository_dispatch:
    type: [new]
jobs:
  new-message:
    runs-on: ubuntu-latest
    name: A job to create message
    steps:
      - name: create message
        uses: white-lucida/microcms-discord-message
        