on:
  repository_dispatch:
    type: [new]
env:
  MICROCMS_API_KEY: ${{secrets.MICROCMS_API_KEY}}
  MICROCMS_SERVICE_ID: ${{secrets.MICROCMS_SERVICE_ID}}
  DISCORD_TOKEN: ${{secrets.DISCORD_TOKEN}}
jobs:
  new-message:
    runs-on: ubuntu-latest
    name: A job to create message
    steps:
      - name: create message
        uses: white-lucida/microcms-discord-message@main
        